import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/dashboard/layout.tsx (Contoh struktur)
export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen overflow-hidden">
      {/* SIDEBAR (Lebar tetap, misal w-64) */}
      <aside className="w-64 bg-slate-900 hidden md:block">
        {/* Isi Sidebar Anda */}
      </aside>

      {/* AREA KONTEN UTAMA */}
      <div className="flex-1 flex flex-col ">
        <Navbar /> {/* Navbar akan mengisi sisa lebar layar */}
        <div className="flex-1 flex flex-col">
        <Sidebar /> {/* Navbar akan mengisi sisa lebar layar */}
        </div>
        <main className="p-6 bg-gray-50 min-h-screen">
          {children}
        </main>
      </div>
      
    </div>
  );
}