import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/dashboard/layout.tsx (Contoh struktur)
export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (

<div className="flex overflow-hidden ">
    <div className="w-64 bg-slate-900 hidden md:block">
      {/* SIDEBAR */}
      <Sidebar />
    </div>
  {/* AREA KONTEN UTAMA */}
  <div className="flex-1 flex flex-col">
    {/* NAVBAR */}
    <div className="flex-1 flex flex-col h-screen">
    <Navbar /> {/* Navbar akan mengisi sisa lebar layar */}
     </div> 

    {/* MAIN CONTENT */}
    <main className="flex-1 p-8 bg-gray-100">
       {children}
    </main>
  </div>
</div>
    
  );
}